### ISSUE TITLE
QUIC选项是否能做到强制QUIC?

### ISSUE THREAD

**Issue by zhangyz1997** [jonm58/ghostcp#13]
这两日访问Google还是时常遭遇RST, 把 www.google.com:443 加入 Edge 的 --origin-to-force-quic-on 参数里面就好转很多，但是这个参数只能逐个逐个域名添加，不支持通配符，能添加的域名有限。正好我看到 ghostcp 中提供quic参数, 但是似乎在config里面加上QUIC也不总是能自动像https那样升级到QUIC? 还是我对QUIC这个选项的理解有问题?

**Comment by jonm58** [comment]
是ghostcp的QUIC有问题

**Comment by zhangyz1997** [comment]
那可惜了，ghostcp在ipv6下用quic看googlevideos还是挺快的，就是时灵时不灵

**Comment by jonm58** [comment]
> 那可惜了，ghostcp在ipv6下用quic看googlevideos还是挺快的，就是时灵时不灵 <img alt="Snipaste_2023-11-03_21-18-24" width="1082" src="https://user-images.githubusercontent.com/22343073/280290069-7b58861f-85e2-4c48-ac51-0da321f75d2b.png">
> 
> 不过说起来Quora的QUIC又能work，就很奇怪: <img alt="Snipaste_2023-11-03_21-16-15" width="721" src="https://user-images.githubusercontent.com/22343073/280289392-47ee35a7-1b58-4044-ac3a-e81efc8e679e.png">

googlevideos试一试加"sat"

**Comment by jonm58** [comment]
IPv4没办法使用QUIC,为什么IPv6就可以用🤨

**Comment by zhangyz1997** [comment]
> > 那可惜了，ghostcp在ipv6下用quic看googlevideos还是挺快的，就是时灵时不灵 <img alt="Snipaste_2023-11-03_21-18-24" width="1082" src="https://user-images.githubusercontent.com/22343073/280290069-7b58861f-85e2-4c48-ac51-0da321f75d2b.png">
> > 不过说起来Quora的QUIC又能work，就很奇怪: <img alt="Snipaste_2023-11-03_21-16-15" width="721" src="https://user-images.githubusercontent.com/22343073/280289392-47ee35a7-1b58-4044-ac3a-e81efc8e679e.png">
> 
> googlevideos试一试加"sat"

已经是了

#Youtube.Video
ipv6=true
method=quic,https,s-seg,sat,df
.googlevideo.com

如果QUIC这问题能解决，那Google系、Meta系、CF系和BBC这四大系列的问题就都解决了
顺便一提，你YouTube.Video那里ipv6=true你写成了ture, 然后 storage.googleapis.com 那里的IP地址里面有一个多了半个 "]" 号

**Comment by jonm58** [comment]
> > > 那可惜了，ghostcp在ipv6下用quic看googlevideos还是挺快的，就是时灵时不灵 <img alt="Snipaste_2023-11-03_21-18-24" width="1082" src="https://user-images.githubusercontent.com/22343073/280290069-7b58861f-85e2-4c48-ac51-0da321f75d2b.png">
> > > 不过说起来Quora的QUIC又能work，就很奇怪: <img alt="Snipaste_2023-11-03_21-16-15" width="721" src="https://user-images.githubusercontent.com/22343073/280289392-47ee35a7-1b58-4044-ac3a-e81efc8e679e.png">
> > 
> > 
> > googlevideos试一试加"sat"
> 
> 已经是了
> 
> #Youtube.Video ipv6=true method=quic,https,s-seg,sat,df .googlevideo.com
> 
> 如果QUIC这问题能解决，那Google系、Meta系、CF系和BBC这四大系列的问题就都解决了 (感觉也是两难，ghostcp彻底用不了DoT/DoH, phantomsocks用不了QUIC) 顺便一提，你YouTube.Video那里ipv6=true你写成了ture, 然后 storage.googleapis.com 那里的IP地址里面有一个多了个 "]" 号

额,你怎么Quora的IP是来自SJC?
我的是HKG.
