### ISSUE TITLE
访问dw和trtworld需不需要IP？

### ISSUE THREAD

**Issue by Phineario** [jonm58/ghostcp#14]
如题，自己把几个世界新闻台写进了default.conf里面，目前澳洲abc和euronews可以正常访问，dw和trtworld无法正常访问，所以想问问访问这两个新闻台需不需要IP，谢谢！
```
method=w-md5,https,df
abc.net.au
.abc.net.au
dw.com
.dw.com
trtworld.com
.trtworld.com
euronews.com
.euronews.com
```

**Comment by jonm58** [comment]
> trtworld.com

dw.com用DNS的2个IP已经没法使用(对于我)
但是www.dw.com应该可以用在dw.com吧?:
`dw.com=www.dw.com`
或者
`dw.com=23.37.156.105,23.65.43.185,23.212.216.68,23.7.110.69,23.49.176.40,23.198.119.34,184.85.155.153,118.215.187.124,184.87.111.117,23.77.13.35,23.215.59.148,23.197.146.18,23.223.83.157,92.123.205.167,184.51.135.176,23.49.124.128`
trtworld.com需要IP
建议:直接用www.dw.com或者www.trtworld.com,用dw.com和trtworld.com麻烦

**Comment by Phineario** [comment]
试了一下，现在几个都能正常访问了
