### ISSUE TITLE
访问google.com显示ERR_SSL_VERSION_OR_CIPHER_MISMATCH，但是YouTube可以正常访问

### ISSUE THREAD

**Issue by Phineario** [jonm58/ghostcp#15]
![image](https://github.com/jonm58/ghostcp/assets/46863206/beb41456-f17d-4de5-8ad4-63d549564016)
油管视频能正常观看，此外油管视频页面使用*.ggpht.com的元素（如头像和点赞按钮等）也能正常显示
![image](https://github.com/jonm58/ghostcp/assets/46863206/13a6d5f0-36f3-48a2-b49c-8a974ef4028c)
是不是需要更新ip了？

![image](https://github.com/jonm58/ghostcp/assets/46863206/8cf0e483-5448-4f33-a067-6376a2e422f8)

**Comment by jonm58** [comment]
> 更新ip

那就更新吧(?)
