### ISSUE TITLE
在开启软件后，gnome.org 上不去了

### ISSUE THREAD

**Issue by wtklrs** [jonm58/ghostcp#21]
下载最新版本后，然后打开 `www.gnome.org` 或者其他子域名 `extensions.gnome.org` 好像上不去了 (直连能上，开启软件不能上)，因为我刚刚使用软件不久，我手动尝试着修改配了，调了很久都没有成功，所以特意来请教一下。如何解决此问题呢？

另外，在修改配置的过程中发现了一些小问题：
1.  gstatic.com 这个域名好像被定义了多次，影响了 `https://translate.google.com/?sl=auto&tl=zh-CN&op=translate` 网站的资源加载，然后我尝试着删除了如下代码，再次重新加载，资源就加载成功了：
```conf
# 2367 行
.metric.gstatic.com

# 2498 行
www.gstatic.com
fonts.gstatic.com
ssl.gstatic.com
csi.gstatic.com
g0.gstatic.com
g1.gstatic.com
g2.gstatic.com
g3.gstatic.com
checkin.gstatic.com
connectivitycheck.gstatic.com
```

上面的代码是和第 1485 行的  `.gstatic.com=[google.com]` 有什么冲突吗？

2.  `1lib.fr` 好像上不去，我就简单更新了下
```conf
# 删除了第 267 行的代码
1lib.fr=195.66.210.33,176.123.7.105
singlelogin.re
singlelogin.se
.singlelogin.re
.singlelogin.se

# 添加了新的代码，最新的域名 `.singlelogin.re` 、 `.singlelogin.rs`、`z-lib.gs`
method=w-md5
singlelogin.re=176.123.7.105,104.21.92.172,172.67.196.147
.singlelogin.re=[singlelogin.re]
```

3, 希望作者能添加下面的域名：
```conf
search.mdosch.de=5.181.50.75
devdocs.io=104.21.59.58,172.67.215.34
```

**Comment by jonm58** [comment]
0. “在开启软件后，gnome.org 上不去了”
问题在于你的网络环境，我这边没有问题，也与软件无关

1. 会改的
.gstatic.com=[google.com]使用美国Google的IP

- www.gstatic.com
- fonts.gstatic.com
- ssl.gstatic.com
- csi.gstatic.com
- g0.gstatic.com
- g1.gstatic.com
- g2.gstatic.com
- g3.gstatic.com
- checkin.gstatic.com
- connectivitycheck.gstatic.com

将使用北京谷翔信息技术有限公司和中国ISP的IP

2. 会改的(1lib.fr已死亡)

3. 会的

**Comment by jonm58** [comment]
https://github.com/jonm58/ghostcp/releases/tag/v0.14.3

**Comment by wtklrs** [comment]
大佬，最新的配置中，第 277 行的 `devdocs.io=[singlelogin.rs]`，他们不是同一个网站，`devdocs.io` 是一个开发文档网站，并不是我们下书的那个 zlib。

**Comment by jonm58** [comment]
> devdocs.io

没事，能用就行

**Comment by wtklrs** [comment]
好的，非常感谢。
