### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by wtklrs** [jonm58/ghostcp#22]
default(debug mode).conf 

- 第 652 行中，`207.241.226.190207.241.226.190` 少了个逗号，应改为 `207.241.226.190,207.241.226.190`
- 第 1297 行，`120.253.253.98 ,` 后面多一个空格

另向您请教一个问题，您是如何来找到网站对应 IP 地址的呢，步骤是什么呢，方便告知吗？ 我发现在最近两天，在 chrome 上，google.com 上不去了，提示什么安全问题，可能是 IP 需要更新了？？？

**Comment by jonm58** [comment]
> 我发现在最近两天，在 chrome 上，google.com 上不去了，提示什么安全问题，可能是 IP 需要更新了？？？

人呢？发图片?

**Comment by wtklrs** [comment]
![2024-07-31_111320](https://github.com/user-attachments/assets/aaa514be-d4cd-4b52-af8f-0ab8b7b4105a)

**Comment by jonm58** [comment]
> ![2024-07-31_111320](https://private-user-images.githubusercontent.com/98470141/353793681-aaa514be-d4cd-4b52-af8f-0ab8b7b4105a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY5NDYsIm5iZiI6MTcyMjQyNjY0NiwicGF0aCI6Ii85ODQ3MDE0MS8zNTM3OTM2ODEtYWFhNTE0YmUtZDRjZC00YjUyLWFmOGYtMGFiOGI3YjQxMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExNTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMGZlNjRmMTMwMDdiYjdkOGJhYjViMjRjN2I2ZGIyMDBjN2I5NmNlNDUyMjk5NTY1ZThkNWUxNzE5ZTQ2ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5FPv7McpZa1j4lqPaK4K9yx78oFKtknmVWoaNXVDbV4)

你可以试试在chrome://flags/中
把chrome://flags/#enable-quic (Experimental QUIC protocol)设置为Enabeld
把chrome://flags/#enable-tls13-kyber (TLS 1.3 hybridized Kyber support)设置为Disabeld

在Firefox中security.tls.enable_kyber和network.http.http3.enable_kyber设置为true,没有问题

**Comment by wtklrs** [comment]
经过设置后，Chrome 可以正常加载了，但 Firefox 会显示 “google.com 的服务器响应时间过长”。嗯，只要 Chrome 能用就好了。

**Comment by wtklrs** [comment]
大佬，是我大意了，上面提到的设置并不能完全解决问题，刚才能连上是因为我忘记了 "我开了代理"。我彻底关了代理，然后彻底更新了 DNS，初次访问 google 时是无法连接成功的，但经过多次手动刷新之后，google.com 才有**几率**打开 （有时候多次刷新也没有用）。为了测试配置的有效性，我将谷歌相关的配置放到了 phantomsocks 上，好像那边没啥问题 (在 linux 上进行的测试)

**Comment by jonm58** [comment]
> 大佬，是我大意了，上面提到的设置并不能完全解决问题，刚才能连上是因为我忘记了 "我开了代理"。我彻底关了代理，然后彻底更新了 DNS，初次访问 google 时是无法连接成功的，但经过多次手动刷新之后，google.com 才有**几率**打开 （有时候多次刷新也没有用）。为了测试配置的有效性，我将谷歌相关的配置放到了 phantomsocks 上，好像那边没啥问题 (在 linux 上进行的测试)

# 嗯？

**Comment by jonm58** [comment]
> 大佬，是我大意了，上面提到的设置并不能完全解决问题，刚才能连上是因为我忘记了 "我开了代理"。我彻底关了代理，然后彻底更新了 DNS，初次访问 google 时是无法连接成功的，但经过多次手动刷新之后，google.com 才有**几率**打开 （有时候多次刷新也没有用）。为了测试配置的有效性，我将谷歌相关的配置放到了 phantomsocks 上，好像那边没啥问题 (在 linux 上进行的测试)

你有没有IPv6?

**Comment by wtklrs** [comment]
有呀

**Comment by jonm58** [comment]
你要么把ipv6=**true**设置为false，要么https://github.com/GoodCoder666/GoogleTranslate_IPFinder 测你那里可以使用的IPv6

**Comment by jonm58** [comment]
https://rvlt.gg/Ws2kexsD
可以在Revolt上说

**Comment by wtklrs** [comment]
更新：
经过仔细确认，网络的 IPv6 是开启的状态。然后我尝试更新了下程序的配置，将 IP 限定为 `google.com=2404:6800:4003:c00::5a,216.239.32.40`。只保留了一个 ipv6 和一个 ipv4。经过多次软件的重启尝试，在 Chrome 上没有遇到问题，IPv6 也是可以访问的。为了测试 Firefox，我重新下载了一个新的 Firefox，经过重试没有遇到问题，之前的 Firefox 问题是浏览器本身问题。
感谢您的指导帮助。
