### ISSUE TITLE
对Hello Retry Request不起作用

### ISSUE THREAD

**Issue by zhengqwe** [jonm58/ghostcp#23]
对Hello Retry Request之后的client hello不起作用

**Comment by jonm58** [comment]
是在浏览器吗?

**Comment by jonm58** [comment]
测试一下这个:https://github.com/jonm58/ghostcp/releases/tag/v0.14.7

**Comment by jonm58** [comment]
> 可以用了，但更好的方法是把Hello Retry Request之后的CH也进行处理

请你另寻他人(开源项目),比如域前置技术
