### ISSUE TITLE
使用后443超时

### ISSUE THREAD

**Issue by Xihihhh** [jonm58/ghostcp#25]
测试 GitHub 和 Google，一直在重置或超时，关掉 GhosTCP 发现 20.27.177.113:443 和 216.239.32.40:443 被封了一会儿。

**Comment by jonm58** [comment]
你的网太快了,建议method加上seq？

**Comment by Xihihhh** [comment]
> 你的网太快了

没看懂。

> 反正我不知道你的default.conf是什么样子的

一直用您的配置。

之前是移动，现在换电信了，GitHub 没问题，Google 先试了 [RC Firefox](https://github.com/runningcheese/RunningCheese-Firefox)，报 SSL_ERROR_BAD_MAC_READ，换官方 Edge 后还是超时，然后 216.239.32.40:443 被重置。还是用域前置好了。

**Comment by jonm58** [comment]
> 没看懂。

我的网络只有4MB，你呢?

**Comment by Xihihhh** [comment]
> 我的网络只有4MB每秒，你呢?

那确实慢

**Comment by Xihihhh** [comment]
电信还是不行，不过没见有超时了

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/a598c174-12dc-4fbc-99f7-34123bd5f053)
![图片](https://github.com/user-attachments/assets/52d20dd1-e439-400c-89b9-4b8f7a64960a)
![图片](https://github.com/user-attachments/assets/834f4726-4958-4e54-835e-eca535885364)
我是广西广电IPTV，算是联通用户(?),广东出口享受者
![图片](https://github.com/user-attachments/assets/2448215f-a3af-490e-90b3-e32f9f4cfacd)
