### ISSUE TITLE
GitHub Workspace

### ISSUE THREAD

**Issue by Xihihhh** [jonm58/ghostcp#27]
几个月前就发现 Workspace 用不了了，报错`ECONNABORTED: (timeout) timeout of 20000ms exceeded`，看日志是 asse.rel.tunnels.api.visualstudio.com:443超时，试着自己加各种 method 没用。

**Comment by jonm58** [comment]
asse.rel.tunnels.api.visualstudio.com的IP只有20.197.80.108，ping是正常的，443是封的
你可以直接在你的浏览器上访问https://20.197.80.108

我这里是封的

**Comment by jonm58** [comment]
> 是先在日志看到超时，本地 ping 发现正常，最后 [ITDOG](https://itdog.cn) tcping 一片红。

只封443端口吗......

**Comment by Xihihhh** [comment]
> 只封443端口吗...... PS:IPv6现在也开始封端口了

对，80没事。我还没用过 IPv6 :(
